version: "3.8"

services:

  # MariaDB database
  mariadb:
      image: mariadb:10.11
      restart: unless-stopped
      environment:
        MARIADB_ROOT_PASSWORD: N3diRox
      volumes:
        - mysqldata:/var/lib/mysql
      networks:
        backend:
          aliases:
            - "mysql"

  # Nginx Service
  nginx:
      build:
        dockerfile: nginx/Dockerfile
      restart: unless-stopped
      ports:
        - 11080:80
        - 11443:443
        - 18080:8080
        - 18443:8443
      links:
        - nedi
#     volumes:
#       - './nedi/files:/var/nedi'
#       - './nginx-conf:/etc/nginx/conf.d'
      depends_on:
        - nedi
      networks:
        - backend

  # NeDi service
  nedi:
      build:
        dockerfile: nedi/Dockerfile
      restart: unless-stopped
      depends_on:
        - mariadb
      environment:
        NEDI_DB_HOST: mariadb
        NEDI_DB_NAME: nedi
        NEDI_DB_USER: root
        NEDI_DB_PASS: N3diRox
      volumes:
        - './nedi/files/db-status:/var/nedi/db-status'
      networks:
        - backend
      ports:
        - 514:514

  # phpMyAdmin Service
  phpmyadmin:
      image: phpmyadmin/phpmyadmin:5-fpm-alpine
      restart: no
      environment:
          PMA_HOST: mariadb
      depends_on:
          - mariadb
      networks:
        - backend

networks:
  backend:
    driver: bridge

# Volumes
volumes:
  mysqldata: