version: "3.8"

services:

  # MariaDB database
  mariadb:
      image: mariadb:10.11
      environment:
        MARIADB_ROOT_PASSWORD: N3diRox
      restart: always
      volumes:
        - mysqldata:/var/lib/mysql
      networks:
        backend:
          aliases:
            - "mysql"

  # Nginx Service
  nginx:
      image: nginx:latest
      ports:
        - 11080:80
        - 11443:443
      links:
        - nedi
      volumes:
        - './nedi-files:/var/www/html'
        - './nginx-conf:/etc/nginx/conf.d'
      depends_on:
        - nedi

  # NeDi service
  nedi:
      build:
        dockerfile: nedi/Dockerfile
      depends_on:
        - mariadb
      environment:
        NEDI_DB_HOST: mariadb
        NEDI_DB_NAME: nedi
        NEDI_DB_USER: root
        NEDI_DB_PASS: N3diRox
#      volumes:
#        - /var/local/docker/nedi/:/var/nedi
      networks:
        - backend
      ports:
        - 514:514

  # phpMyAdmin Service
  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      ports:
          - 18080:80
      environment:
          PMA_HOST: mariadb
      depends_on:
          - mariadb

networks:
  backend:
    driver: bridge

# Volumes
volumes:
  mysqldata: