version: "3.8"

services:

  # MariaDB database
  mariadb:
      image: mariadb:10.11
      restart: unless-stopped
      environment:
        MARIADB_ROOT_PASSWORD: N3diRox
      volumes:
        - mysqldata:/var/lib/mysql
      networks:
        backend:
          aliases:
            - "mysql"

  # Nginx Service
  nginx:
      build:
        dockerfile: nginx/Dockerfile
      restart: unless-stopped
      ports:
        - 80:80
        - 443:443
#       - 8080:8080
        - 8443:8443
      links:
        - nedi
      volumes:
        - 'nedifiles:/var/nedi/'
#       - './nginx-conf:/etc/nginx/conf.d'
#       - './ssl:/etc/ssl/'
      depends_on:
        - nedi
      networks:
        - backend

  # NeDi service
  nedi:
      build:
        dockerfile: nedi/Dockerfile
      restart: unless-stopped
      depends_on:
        - mariadb
      environment:
        NEDI_DB_HOST: mariadb
        NEDI_DB_NAME: nedi
        NEDI_DB_USER: root
        NEDI_DB_PASS: N3diRox
        TZ: 'Europe/Vaduz'
      volumes:
        - 'nedifiles:/var/nedi/'
      networks:
        - backend
      ports:
        - 514:1514

  # Adminer Service
  adminer:
      image: adminer:fastcgi
      restart: unless-stopped
      environment:
          ADMINER_DEFAULT_SERVER: mariadb
          ADMINER_DESIGN: 'galkaev'
      depends_on:
        - mariadb
      networks:
        - backend

networks:
  backend:
    driver: bridge

# Volumes
volumes:
  mysqldata:
  nedifiles: