version: "3.1"
services:
  db:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: N3diRox
      MARIADB_DATABASE: nedi
    restart: always
    volumes:
      - /var/local/docker/nedi/mysql/etc:/etc/mysql
      - /var/local/docker/nedi/mysql:/var/lib/mysql
    networks:
      - backend
  nedi:
    depends_on:
      - db
    image: klinnex/nedi
    environment:
      NEDI_DB_HOST: mariadb
      NEDI_DB_NAME: nedi
      NEDI_DB_USER: root
      NEDI_DB_PASS: N3diRox
    volumes:
      - /var/local/docker/nedi/:/var/nedi
    ports:
      - "80:80"
      - "514:514"
    networks:
      - frontend
      - backend
networks:
  frontend:
    driver: bridge         
  backend:
    driver: bridge
